version: "3.8"

services:
  nodered:
    image: nodered/node-red:latest
    container_name: mynodered
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
      - ./settings.js:/data/settings.js   # Optional: custom settings
    restart: unless-stopped