version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DigitalFrontiersDB
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - df-network

  backend:
    image: node:18
    container_name: backend
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/DigitalFrontiersDB
    command: >
      sh -c "
      if [ ! -d /app/.git ]; then
        git clone --branch develop https://github.com/syk-yaman/shift-digital-frontiers.git /app;
      else
        cd /app && git fetch && git checkout develop && git pull;
      fi &&
      cd /app/src/backend &&
      npm install &&
      npm run typeorm -- migration:run -d ./data-source.ts &&
      npm run start:dev"
    ports:
      - "3000:3000"
    networks:
      - df-network

  frontend:
    image: node:18
    container_name: frontend
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "
      if [ ! -d /app/.git ]; then
        git clone --branch develop https://github.com/syk-yaman/shift-digital-frontiers.git /app;
      else
        cd /app && git fetch && git checkout develop && git pull;
      fi &&
      cd /app/src/frontend &&
      npm install &&
      npm run build &&
      npx serve -s dist -l tcp:0.0.0.0:3001"
    ports:
      - "3001:3001"
    networks:
      - df-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - frontend
      - backend
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - df-network

networks:
  df-network:
    driver: bridge